name = "HypertextTools"
uuid = "4502ade7-0b84-4acc-96da-75e5ce1d0abd"
authors = ["Tsung-Hsi Wu <okatsn@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
julia = "1.6.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
